#!/usr/bin/env node
// Generates data/seed.sql — demo data for the whole Phase 0–1 surface.
//
// Dates are written as SQLite expressions relative to "now" (date('now',
// '+12 days')), so the demo never goes stale: there is always something
// overdue, something due today and a project in its tenth month.
//
//   node scripts/generate-seed.mjs && npm run db:seed
//
// Fictional people and partners; real programme names.

import { writeFileSync, readFileSync } from 'node:fs';

const out = [];
const q = (v) => v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : typeof v === 'object' && v.sql ? v.sql : `'${String(v).replace(/'/g, "''")}'`;
const d = (days) => ({ sql: `date('now', '${days >= 0 ? '+' : ''}${days} days')` });
const ts = (days, hours = 0) => ({ sql: `strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '${days >= 0 ? '+' : ''}${days} days', '${hours >= 0 ? '+' : ''}${hours} hours')` });
const monthStart = (m) => ({ sql: `date('now', 'start of month', '${m >= 0 ? '+' : ''}${m} months')` });
// Last day of project month M for a project starting monthStart(startOffset).
const pm = (startOffset, M) => ({ sql: `date('now', 'start of month', '${startOffset >= 0 ? '+' : ''}${startOffset + M} months', '-1 day')` });
function ins(table, row) {
  const k = Object.keys(row);
  out.push(`INSERT INTO ${table} (${k.join(', ')}) VALUES (${k.map(x => q(row[x])).join(', ')});`);
}
const section = (s) => out.push('', `-- ${s}`);

out.push('-- Demo data for KMOP HQ. Generated by scripts/generate-seed.mjs — edit that, not this.',
  '-- Apply after migrations: npm run db:seed. Every date is relative to the day you load it.', '');

// ---------------------------------------------------------------------------
section('Entities. ASSUMPTION: KMOP POLICY CENTER is the Brussels entity; ASSOCIATION and EDUCATION HUB are in Athens. Fix in Administration → Entities if not.');
ins('entities', { id: 1, code: 'ASSOC', name: 'KMOP ASSOCIATION', legal_name: 'KMOP – Social Action and Innovation Centre', country: 'GR', city: 'Athens', vat_number: 'EL090000001', pic: '949000001', oid: 'E10000001', currency: 'EUR', timezone: 'Europe/Athens', color: '#2563eb' });
ins('entities', { id: 2, code: 'POLICY', name: 'KMOP POLICY CENTER', legal_name: 'KMOP Policy Center AISBL', country: 'BE', city: 'Brussels', vat_number: 'BE0700000002', pic: '949000002', oid: 'E10000002', currency: 'EUR', timezone: 'Europe/Brussels', color: '#7c3aed' });
ins('entities', { id: 3, code: 'EDU', name: 'KMOP EDUCATION HUB', legal_name: 'KMOP Education Hub', country: 'GR', city: 'Athens', vat_number: 'EL090000003', pic: '949000003', oid: 'E10000003', currency: 'EUR', timezone: 'Europe/Athens', color: '#059669' });

section('Departments. Management and Communications span all entities, so they have no entity.');
const depts = [
  [1, null, 'Management', 'Διοίκηση'], [2, 1, 'Projects & Programmes', 'Έργα & Προγράμματα'], [3, 1, 'Finance', 'Οικονομικά'],
  [4, 2, 'EU Policy & Advocacy', 'Ευρωπαϊκή Πολιτική'], [5, 3, 'Training & Education', 'Εκπαίδευση & Κατάρτιση'], [6, null, 'Communications', 'Επικοινωνία'],
];
for (const [id, entity_id, name, name_el] of depts) ins('departments', { id, entity_id, name, name_el });

section('People');
const people = [
  // id, email, name, title, entity, dept, weekly, days, locale, external org
  [1, 'k.antonopoulou@kmop.org', 'Katerina Antonopoulou', 'General Manager', 1, 1, 40, '12345', 'el'],
  [2, 'n.papadakis@kmop.org', 'Nikos Papadakis', 'Deputy Director', 1, 1, 40, '12345', 'el'],
  [3, 'e.georgiou@kmop.org', 'Eleni Georgiou', 'Head of Projects', 1, 2, 40, '12345', 'el'],
  [4, 'd.kostopoulos@kmop.org', 'Dimitris Kostopoulos', 'Senior Project Manager', 1, 2, 40, '12345', 'el'],
  [5, 'm.ioannou@kmop.org', 'Maria Ioannou', 'Project Officer', 1, 2, 40, '12345', 'el'],
  [6, 'g.nikolaou@kmop.org', 'Giorgos Nikolaou', 'Training Coordinator', 3, 5, 40, '12345', 'el'],
  [7, 's.lambert@kmop.org', 'Sophie Lambert', 'EU Project Manager', 2, 4, 40, '12345', 'en'],
  [8, 't.verbeke@kmop.org', 'Thomas Verbeke', 'Policy Officer', 2, 4, 32, '1234', 'en'],
  [9, 'a.papadopoulou@kmop.org', 'Anna Papadopoulou', 'Finance Manager', 1, 3, 40, '12345', 'el'],
  [10, 'l.dubois@kmop.org', 'Lucas Dubois', 'Finance Officer (Brussels)', 2, 3, 40, '12345', 'en'],
  [11, 'c.alexiou@kmop.org', 'Christina Alexiou', 'Trainer (part-time)', 3, 5, 24, '123', 'el'],
  [12, 'y.markou@kmop.org', 'Yannis Markou', 'IT & Systems', 1, 1, 40, '12345', 'en'],
  [13, 'p.vlachou@kmop.org', 'Penelope Vlachou', 'Communications Officer', 1, 6, 40, '12345', 'el'],
];
for (const [id, email, name, title, entity_id, department_id, weekly_hours, work_days, locale] of people) {
  ins('users', { id, email, name, title, entity_id, department_id, weekly_hours, work_days, locale, manager_id: id === 1 ? null : id <= 3 ? 1 : department_id === 4 ? 2 : 3, last_login_at: ts(-1, -3) });
}
ins('users', { id: 14, email: 'laura.rossi@progettieuropei.example', name: 'Laura Rossi', title: 'Project Coordinator', is_external: 1, external_org: 'Associazione Progetti Europei (IT)', locale: 'en', weekly_hours: 0 });
ins('users', { id: 15, email: 'audit@ey-audit.example', name: 'Petros Lazaridis', title: 'External auditor', entity_id: null, external_org: 'Audit firm (time-boxed access)', locale: 'el', weekly_hours: 0 });
out.push(`UPDATE departments SET head_user_id = 1 WHERE id = 1; UPDATE departments SET head_user_id = 3 WHERE id = 2; UPDATE departments SET head_user_id = 9 WHERE id = 3;`,
  `UPDATE departments SET head_user_id = 7 WHERE id = 4; UPDATE departments SET head_user_id = 6 WHERE id = 5; UPDATE departments SET head_user_id = 13 WHERE id = 6;`);
for (const [id, , , , , , , , ] of people) ins('auth_identities', { user_id: id, provider: 'email', subject: people.find(p => p[0] === id)[1] });

section('Roles. Note the scoping: Anna is finance for the two Greek entities only, Lucas for Brussels only; Eleni heads one department.');
const roles = [
  [1, 'general_manager', null, null], [2, 'upper_management', null, null], [3, 'department_head', null, 2], [3, 'project_manager', null, null],
  [4, 'project_manager', null, null], [5, 'team_member', null, null], [6, 'team_member', null, null], [6, 'department_head', null, 5],
  [7, 'project_manager', null, null], [7, 'department_head', null, 4], [8, 'team_member', null, null],
  [9, 'finance', 1, null], [9, 'finance', 3, null], [9, 'team_member', null, null], [10, 'finance', 2, null], [10, 'team_member', null, null],
  [11, 'team_member', null, null], [12, 'super_admin', null, null], [13, 'team_member', null, null], [14, 'external_partner', null, null],
];
for (const [user_id, role, entity_id, department_id] of roles) ins('user_roles', { user_id, role, entity_id, department_id, granted_by: 12 });
ins('user_roles', { user_id: 15, role: 'auditor', valid_until: d(45), granted_by: 12 });
ins('module_access', { user_id: 2, module: 'salaries', entity_id: 1, level: 1, reason: 'Signs payroll for KMOP ASSOCIATION', granted_by: 12 });

section('Public holidays (a few, enough to show workload honouring them)');
const grHol = [['10-28', 'Ochi Day / Επέτειος του Όχι'], ['12-25', 'Christmas / Χριστούγεννα'], ['12-26', 'Synaxis of the Theotokos'], ['01-01', 'New Year'], ['01-06', 'Epiphany / Θεοφάνεια']];
const beHol = [['11-01', 'All Saints'], ['11-11', 'Armistice Day'], ['12-25', 'Christmas'], ['01-01', 'New Year']];
for (const y of ['2026', '2027']) {
  for (const [md, name] of grHol) { ins('entity_holidays', { entity_id: 1, date: `${y}-${md}`, name }); ins('entity_holidays', { entity_id: 3, date: `${y}-${md}`, name }); }
  for (const [md, name] of beHol) ins('entity_holidays', { entity_id: 2, date: `${y}-${md}`, name });
}

section('Leave');
ins('leave', { user_id: 5, start_date: d(9), end_date: d(13), kind: 'annual', created_by: 5 });
ins('leave', { user_id: 7, start_date: d(2), end_date: d(2), kind: 'training', half_day: 1, note: 'EU funding info day', created_by: 7 });
ins('leave', { user_id: 6, start_date: d(-3), end_date: d(-2), kind: 'sick', created_by: 6 });
ins('leave', { user_id: 4, start_date: d(21), end_date: d(30), kind: 'annual', created_by: 4 });

// ---------------------------------------------------------------------------
section('Projects');
// YOUTHLINK started 9 months ago (we are in M10 of 24); SAFE-CERV 4 months ago; the ESPA project 2 months ago.
const P = {
  youth: { id: 1, start: -9, months: 24 }, cerv: { id: 2, start: -4, months: 24 }, espa: { id: 3, start: -2, months: 18 }, hq: { id: 4, start: 0, months: 6 },
};
ins('projects', { id: 1, entity_id: 1, department_id: 2, code: 'YOUTHLINK', name: 'YouthLink — Digital youth work across borders', kind: 'eu', funder: 'Erasmus+ KA220-YOU (Cooperation partnerships in youth)', our_role: 'partner',
  status: 'active', start_date: monthStart(-9), end_date: pm(-9, 24), color: '#2563eb', description: 'Cooperation partnership led by Associazione Progetti Europei (IT) with partners in GR, ES and PL. KMOP leads **WP3 — Training toolkit** and contributes to WP2, WP4 and WP5.\n\n- Grant: €250,000 lump sum (KMOP share €48,500)\n- Project number: 2025-1-IT03-KA220-YOU-000000001', created_by: 3, last_activity_at: ts(0, -2) });
ins('projects', { id: 2, entity_id: 2, department_id: 4, code: 'SAFE-CERV', name: 'SAFE — Preventing gender-based violence in schools', kind: 'eu', funder: 'CERV-2025-DAPHNE', our_role: 'coordinator',
  status: 'active', start_date: monthStart(-4), end_date: pm(-4, 24), color: '#7c3aed', description: 'KMOP POLICY CENTER coordinates a consortium of 6 partners (BE, GR, CY, RO, HR, PT). Actual-cost budget with 90% EU co-financing.', created_by: 7, last_activity_at: ts(0, -5) });
ins('projects', { id: 3, entity_id: 3, department_id: 5, code: 'DIGI50', name: 'Ψηφιακές Δεξιότητες 50+ (Digital skills for adults 50+)', kind: 'national', funder: 'ΕΣΠΑ 2021–2027 — Περιφέρεια Αττικής', our_role: 'sole beneficiary',
  status: 'active', start_date: monthStart(-2), end_date: pm(-2, 18), color: '#059669', description: 'Πράξη ΕΣΠΑ: 12 κύκλοι κατάρτισης για 240 ωφελούμενους 50+. Physical progress reported per training cycle; subsidy instalments tied to milestones.', created_by: 4, last_activity_at: ts(-1) });
ins('projects', { id: 4, entity_id: 1, department_id: 1, code: 'HQ', name: 'KMOP HQ rollout', kind: 'internal', status: 'active', start_date: monthStart(0), end_date: pm(0, 6), visibility: 'entity', color: '#64748b', description: 'Moving project work from spreadsheets into KMOP HQ.', created_by: 12, last_activity_at: ts(-3) });

section('Members. Several PMs per project is normal; Laura is a guest from the lead partner.');
const members = [
  [1, 3, 'pm'], [1, 4, 'pm'], [1, 5, 'member'], [1, 6, 'member'], [1, 13, 'member'], [1, 14, 'guest'], [1, 9, 'viewer'],
  [2, 7, 'pm'], [2, 8, 'member'], [2, 10, 'member'], [2, 13, 'member'], [2, 5, 'member'],
  [3, 4, 'pm'], [3, 6, 'member'], [3, 11, 'member'], [3, 9, 'member'],
  [4, 12, 'pm'], [4, 1, 'member'], [4, 3, 'member'],
];
for (const [project_id, user_id, role] of members) ins('project_members', { project_id, user_id, role, added_by: project_id === 2 ? 7 : project_id === 4 ? 12 : 3, added_at: ts(-200) });

section('Allocations (planned FTE per person per project)');
const alloc = [[3, 1, 20, 4.8], [4, 1, 30, 7.2], [5, 1, 50, 12], [6, 1, 20, 4.8], [7, 2, 60, 14.4], [8, 2, 50, 12], [10, 2, 20, 4.8], [5, 2, 30, 7.2], [4, 3, 30, 5.4], [6, 3, 60, 10.8], [11, 3, 80, 14.4], [9, 3, 10, 1.8]];
for (const [user_id, project_id, fte_pct, person_months] of alloc) {
  const p = Object.values(P).find(x => x.id === project_id);
  ins('allocations', { user_id, project_id, start_date: monthStart(p.start), end_date: pm(p.start, p.months), fte_pct, person_months, created_by: 3 });
}

section('Sections');
const sections = {
  1: ['WP1 — Management', 'WP2 — Research', 'WP3 — Training toolkit (KMOP lead)', 'WP4 — Pilots', 'WP5 — Dissemination'],
  2: ['Coordination', 'WP2 — School programme', 'WP3 — Awareness campaign', 'Reporting'],
  3: ['Προετοιμασία', 'Κύκλοι κατάρτισης', 'Φυσικό & οικονομικό αντικείμενο'],
  4: ['Setup', 'Training', 'Migration'],
};
let sid = 1; const S = {};
for (const [pid, names] of Object.entries(sections)) names.forEach((name, i) => { S[`${pid}:${i}`] = sid; ins('sections', { id: sid++, project_id: Number(pid), name, position: i + 1 }); });

section('Labels');
const labels = [[1, null, 'partner-input', '#0ea5e9'], [2, null, 'finance', '#16a34a'], [3, null, 'urgent', '#dc2626'], [4, 1, 'toolkit', '#9333ea'], [5, 2, 'safeguarding', '#db2777'], [6, 3, 'ΕΣΠΑ', '#ca8a04']];
for (const [id, project_id, name, color] of labels) ins('labels', { id, project_id, name, color });

section('Custom fields');
ins('custom_fields', { id: 1, project_id: 1, name: 'Lead partner', type: 'select', position: 1, options: JSON.stringify([{ key: 'ape', label: 'APE (IT)' }, { key: 'kmop', label: 'KMOP (GR)' }, { key: 'fes', label: 'FES (ES)' }, { key: 'mlp', label: 'MLP (PL)' }]) });
ins('custom_fields', { id: 2, project_id: 1, name: 'Dissemination level', type: 'select', position: 2, options: JSON.stringify([{ key: 'pu', label: 'Public' }, { key: 'se', label: 'Sensitive' }]) });
ins('custom_fields', { id: 3, project_id: 2, name: 'Partner', type: 'text', position: 1 });
ins('custom_fields', { id: 4, project_id: 3, name: 'Αρ. πρωτοκόλλου', type: 'text', position: 1 });
ins('custom_fields', { id: 5, project_id: 3, name: 'Ωφελούμενοι', type: 'number', position: 2 });

// ---------------------------------------------------------------------------
section('Tasks');
let tid = 1;
const T = {}, TP = {};
function task(key, o) {
  const id = tid++;
  T[key] = id; TP[key] = o.p ?? null;
  const doneDays = o.done; // days ago it was completed (or undefined)
  ins('tasks', {
    id, project_id: o.p ?? null, parent_id: o.parent ? T[o.parent] : null, section_id: o.s != null ? S[`${o.p}:${o.s}`] : null,
    title: o.title, description: o.desc ?? null, status: o.status || (doneDays != null ? 'done' : 'todo'), priority: o.prio || 'none',
    assignee_id: o.a ?? null, start_date: o.start != null ? (typeof o.start === 'object' ? o.start : d(o.start)) : null,
    due_date: o.due != null ? (typeof o.due === 'object' ? o.due : d(o.due)) : null, estimate_hours: o.est ?? null,
    is_milestone: o.ms ? 1 : 0, is_internal: o.internal ? 1 : 0, position: o.pos ?? id,
    completed_at: doneDays != null ? ts(-doneDays) : null, completed_by: doneDays != null ? o.a ?? o.by : null,
    assigned_at: o.a ? ts(-(o.age ?? 20)) : null, created_by: o.by || 3, created_at: ts(-(o.age ?? 30)), updated_at: ts(-(doneDays ?? Math.min(o.age ?? 5, 5))),
  });
  ins('task_followers', { task_id: id, user_id: o.by || 3, reason: 'creator' });
  if (o.a && o.a !== (o.by || 3)) ins('task_followers', { task_id: id, user_id: o.a, reason: 'assignee' });
  for (const l of o.labels || []) ins('task_labels', { task_id: id, label_id: l });
  (o.check || []).forEach((c, i) => {
    const done = Array.isArray(c);
    ins('checklist_items', { task_id: id, text: done ? c[0] : c, done: done ? 1 : 0, done_by: done ? o.a : null, done_at: done ? ts(-2) : null, position: i + 1 });
  });
  for (const [f, v] of Object.entries(o.fields || {})) ins('task_field_values', { task_id: id, field_id: Number(f), value: JSON.stringify(v), value_num: typeof v === 'number' ? v : null });
  return id;
}

// YOUTHLINK — KMOP is a partner, leads WP3. We are in M10.
const Y = 1;
task('y-kick', { p: Y, s: 0, title: 'Attend kick-off meeting in Bologna', a: 4, by: 4, start: pm(-9, 1), due: pm(-9, 1), done: 260, est: 16, ms: 1, age: 280 });
task('y-qplan', { p: Y, s: 0, title: 'Contribute to the quality assurance plan', a: 5, start: pm(-9, 2), due: pm(-9, 3), done: 200, est: 8, age: 270 });
task('y-int1', { p: Y, s: 0, title: 'Interim partner report to the coordinator (M12)', desc: 'APE needs our narrative input and **timesheets** for the interim report. Use the template they circulated.\n\n- Narrative per WP\n- Timesheets M1–M12\n- Proof of dissemination', a: 4, by: 3, start: 25, due: pm(-9, 12), est: 12, prio: 'high', labels: [1, 2], check: ['Collect timesheets from Maria and Giorgos', 'Draft WP3 narrative', 'Attach dissemination evidence'], fields: { 1: 'ape' }, age: 10 });
task('y-tpm3', { p: Y, s: 0, title: 'Transnational meeting 3 — Kraków logistics', a: 5, start: 30, due: 45, est: 10, labels: [1], age: 6 });
task('y-desk', { p: Y, s: 1, title: 'Desk research: digital youth work in Greece', a: 5, start: pm(-9, 2), due: pm(-9, 4), done: 150, est: 40, age: 260 });
task('y-focus', { p: Y, s: 1, title: 'Run two focus groups with youth workers', a: 6, start: pm(-9, 3), due: pm(-9, 5), done: 120, est: 24, age: 250 });
task('y-rep2', { p: Y, s: 1, title: 'National report for the comparative study (D2.1 input)', a: 5, start: pm(-9, 4), due: pm(-9, 6), done: 95, est: 30, fields: { 1: 'fes', 2: 'pu' }, age: 240 });
// WP3: the meat. Toolkit modules with subtasks and dependencies.
task('y-wp3', { p: Y, s: 2, title: 'D3.1 Training toolkit for digital youth work', desc: 'KMOP leads. Five modules, partner review, then translation into IT/ES/PL/EL.\n\nDue at **M14**. Partners review modules in turn — see dependencies.', a: 3, start: pm(-9, 7), due: pm(-9, 14), est: 20, prio: 'high', labels: [4], fields: { 1: 'kmop', 2: 'pu' }, age: 90 });
task('y-wp3-outline', { p: Y, parent: 'y-wp3', title: 'Toolkit outline and learning outcomes', a: 3, start: pm(-9, 7), due: pm(-9, 7), done: 70, est: 10, age: 90 });
task('y-wp3-m1', { p: Y, parent: 'y-wp3', title: 'Module 1 — Online safety', a: 5, start: -40, due: -12, est: 24, labels: [4], age: 60, status: 'in_review', check: [['Draft text'], ['Exercises'], 'Partner review comments addressed'] });
task('y-wp3-m2', { p: Y, parent: 'y-wp3', title: 'Module 2 — Digital storytelling', a: 6, start: -20, due: -3, est: 24, labels: [4], age: 40, status: 'in_progress', prio: 'high' });
task('y-wp3-m3', { p: Y, parent: 'y-wp3', title: 'Module 3 — Media literacy', a: 5, start: 0, due: 18, est: 24, labels: [4], age: 30 });
task('y-wp3-m4', { p: Y, parent: 'y-wp3', title: 'Module 4 — Youth participation online', a: 14, by: 3, start: 10, due: 30, est: 24, labels: [4, 1], age: 30 });
task('y-wp3-m5', { p: Y, parent: 'y-wp3', title: 'Module 5 — Wellbeing and screen time', a: 6, start: 25, due: 50, est: 24, labels: [4], age: 30 });
task('y-wp3-rev', { p: Y, parent: 'y-wp3', title: 'Partner review round', a: 3, start: 50, due: 65, est: 8, labels: [1], age: 30 });
task('y-wp3-tr', { p: Y, parent: 'y-wp3', title: 'Translations IT / ES / PL / EL', a: 4, start: 66, due: pm(-9, 14), est: 6, labels: [1, 2], age: 30, check: ['Get quotes from 3 translators', 'Procurement note (below €2,500 — direct award)', 'Send final EN text'] });
task('y-wp3-m2-a', { p: Y, parent: 'y-wp3-m2', title: 'Collect three example stories from Greek youth centres', a: 6, due: -5, done: 4, est: 6, age: 30 });
task('y-wp3-m2-b', { p: Y, parent: 'y-wp3-m2', title: 'Write activity sheets', a: 6, due: 2, est: 10, age: 30 });
task('y-wp3-ms', { p: Y, s: 2, title: 'Milestone: toolkit ready for piloting', a: 3, due: pm(-9, 14), ms: 1, age: 90 });
task('y-wp3-chase', { p: Y, s: 2, title: 'Chase FES for Module 4 peer review', desc: 'FES has not replied to two emails about the review schedule. Internal — not visible to partner guests.', a: 4, due: -4, est: 1, internal: 1, prio: 'urgent', labels: [3], age: 12 });
task('y-pilot', { p: Y, s: 3, title: 'Pilot the toolkit with 20 youth workers in Athens', a: 6, start: pm(-9, 15), due: pm(-9, 18), est: 60, age: 30, fields: { 1: 'kmop' } });
task('y-pilot-rec', { p: Y, s: 3, title: 'Recruit pilot participants', a: 5, start: pm(-9, 13), due: pm(-9, 14), est: 12, age: 20 });
task('y-dissem', { p: Y, s: 4, title: 'Quarterly social media post on project progress', a: 13, due: 5, est: 2, labels: [], age: 20 });
task('y-news', { p: Y, s: 4, title: 'Newsletter #2 — Greek translation', a: 13, due: -1, est: 3, age: 15, status: 'in_progress' });
task('y-mpe', { p: Y, s: 4, title: 'Multiplier event in Athens (E3)', a: 4, start: pm(-9, 20), due: pm(-9, 21), est: 40, ms: 1, age: 20 });

// SAFE-CERV — KMOP coordinates. M5 now.
const C = 2;
task('c-ga', { p: C, s: 0, title: 'Grant agreement signature and consortium agreement', a: 7, by: 7, due: pm(-4, 1), done: 110, est: 20, age: 140 });
task('c-kick', { p: C, s: 0, title: 'Kick-off meeting (Brussels)', a: 7, by: 7, start: pm(-4, 1), due: pm(-4, 2), done: 95, est: 30, ms: 1, age: 130 });
task('c-prefin', { p: C, s: 0, title: 'Distribute pre-financing to partners', desc: 'Pre-financing received from the Commission. Transfer partner shares per the consortium agreement.', a: 10, by: 7, due: -20, done: 18, est: 6, labels: [2], age: 40, check: [['CY partner'], ['RO partner'], ['HR partner'], ['PT partner'], ['GR partner']] });
task('c-mgmt', { p: C, s: 0, title: 'Monthly consortium call', a: 7, by: 7, due: 6, est: 2, age: 25 });
task('c-risk', { p: C, s: 0, title: 'Review the risk register with partners', a: 8, by: 7, due: 12, est: 3, age: 10 });
task('c-cur', { p: C, s: 1, title: 'D2.1 School programme curriculum', a: 8, by: 7, start: pm(-4, 3), due: pm(-4, 7), est: 80, prio: 'high', labels: [5], fields: { 3: 'KMOP + CY partner' }, age: 60, status: 'in_progress' });
task('c-cur-a', { p: C, parent: 'c-cur', title: 'Literature review on school-based prevention', a: 8, by: 7, due: -25, done: 22, est: 20, age: 60 });
task('c-cur-b', { p: C, parent: 'c-cur', title: 'Teacher session plans (6 sessions)', a: 5, by: 7, start: -10, due: 20, est: 30, labels: [5], age: 30 });
task('c-cur-c', { p: C, parent: 'c-cur', title: 'Safeguarding protocol for facilitators', a: 8, by: 7, due: 30, est: 12, labels: [5], age: 30 });
task('c-ethics', { p: C, s: 1, title: 'Ethics approval for working with minors', a: 7, by: 7, due: -2, est: 8, prio: 'urgent', labels: [5, 3], age: 25, status: 'blocked', desc: 'Waiting on the RO partner\'s national ethics committee letter.' });
task('c-camp', { p: C, s: 2, title: 'Awareness campaign concept', a: 13, by: 7, start: 15, due: 45, est: 24, age: 15 });
task('c-camp-brief', { p: C, s: 2, title: 'Agency brief for campaign visuals', a: 13, by: 7, due: 35, est: 6, age: 15, check: ['Brand guidelines', 'EU emblem and disclaimer', 'Budget ceiling'] });
task('c-ts', { p: C, s: 3, title: 'Collect partner timesheets for M1–M6', a: 10, by: 7, due: 25, est: 6, labels: [2, 1], age: 5 });
task('c-tr1', { p: C, s: 3, title: 'Continuous reporting: deliverable D1.1 Project handbook', a: 7, by: 7, due: pm(-4, 3), done: 50, est: 12, age: 100 });

// DIGI50 — national ESPA project.
const N = 3;
task('n-inc', { p: N, s: 0, title: 'Ένταξη πράξης — έλεγχος απόφασης ένταξης', a: 4, by: 4, due: -50, done: 48, est: 4, labels: [6], age: 70 });
task('n-tender', { p: N, s: 0, title: 'Διαγωνισμός για προμήθεια tablets (κάτω από όριο)', desc: 'Απευθείας ανάθεση — τρεις προσφορές. Έλεγχος ορίων ΕΣΠΑ.', a: 9, by: 4, due: 8, est: 10, labels: [6, 2], age: 30, status: 'in_progress', check: [['Τεχνικές προδιαγραφές'], 'Τρεις προσφορές', 'Απόφαση ανάθεσης'], fields: { 4: '2026/1187' } });
task('n-recruit', { p: N, s: 0, title: 'Recruit trainees for cycles 1–3 (60 people)', a: 11, by: 4, start: -30, due: 10, est: 30, age: 30, fields: { 5: 41 }, status: 'in_progress' });
task('n-c1', { p: N, s: 1, title: 'Κύκλος 1 — Αμπελόκηποι', a: 11, by: 4, start: -14, due: 14, est: 40, age: 20, status: 'in_progress', fields: { 5: 20 } });
task('n-c2', { p: N, s: 1, title: 'Κύκλος 2 — Πειραιάς', a: 6, by: 4, start: 15, due: 45, est: 40, age: 20, fields: { 5: 20 } });
task('n-c3', { p: N, s: 1, title: 'Κύκλος 3 — Περιστέρι', a: 11, by: 4, start: 46, due: 76, est: 40, age: 20, fields: { 5: 20 } });
task('n-phys', { p: N, s: 2, title: 'Δελτίο παρακολούθησης φυσικού αντικειμένου (τρίμηνο)', a: 4, by: 4, due: 16, est: 6, labels: [6], age: 10, prio: 'high' });
task('n-fin', { p: N, s: 2, title: 'Αίτημα καταβολής 1ης δόσης', desc: 'Η 1η δόση συνδέεται με την ολοκλήρωση του Κύκλου 1 (ορόσημο).', a: 9, by: 4, due: 20, est: 8, labels: [6, 2], age: 10 });
task('n-ms1', { p: N, s: 2, title: 'Ορόσημο: Ολοκλήρωση Κύκλου 1', a: 4, by: 4, due: 14, ms: 1, age: 20 });

// HQ rollout (internal)
const H = 4;
task('h-setup', { p: H, s: 0, title: 'Configure entities, departments and roles', a: 12, by: 12, due: -5, done: 4, est: 6, age: 10 });
task('h-train', { p: H, s: 1, title: 'Training session for project managers', a: 3, by: 12, due: 9, est: 4, age: 5 });
task('h-mig', { p: H, s: 2, title: 'Move YOUTHLINK task list from the shared spreadsheet', a: 4, by: 12, due: 3, est: 3, age: 5, status: 'in_progress' });

// Personal tasks (no project)
task('me-1', { title: 'Prepare 1:1 notes for Maria', a: 3, by: 3, due: 1, est: 1, age: 2 });
task('me-2', { title: 'Book flights for Kraków meeting', a: 5, by: 5, due: 7, est: 1, age: 3 });
task('me-3', { title: 'Read the CERV call FAQ', a: 7, by: 7, est: 2, age: 3 });

section('Dependencies (blocks / blocked by)');
const deps = [
  ['y-wp3-outline', 'y-wp3-m1'], ['y-wp3-outline', 'y-wp3-m2'], ['y-wp3-m1', 'y-wp3-m3'], ['y-wp3-m2', 'y-wp3-m4'], ['y-wp3-m3', 'y-wp3-m5'],
  ['y-wp3-m4', 'y-wp3-rev'], ['y-wp3-m5', 'y-wp3-rev'], ['y-wp3-rev', 'y-wp3-tr'], ['y-wp3-tr', 'y-wp3-ms'], ['y-wp3-ms', 'y-pilot'], ['y-pilot-rec', 'y-pilot'],
  ['y-desk', 'y-rep2'], ['y-focus', 'y-rep2'],
  ['c-ga', 'c-prefin'], ['c-cur-a', 'c-cur-b'], ['c-ethics', 'c-cur-b'], ['c-camp', 'c-camp-brief'],
  ['n-recruit', 'n-c1'], ['n-c1', 'n-ms1'], ['n-ms1', 'n-fin'], ['n-c1', 'n-c2'], ['n-c2', 'n-c3'],
];
for (const [a, b] of deps) ins('task_dependencies', { blocker_id: T[a], blocked_id: T[b], created_by: 3 });

section('Recurring rituals');
ins('recurrences', { id: 1, freq: 'monthly', interval_n: 1, by_monthday: 5, mode: 'schedule', next_due: { sql: `date('now', 'start of month', '+1 month', '+4 days')` }, source_task_id: null, created_by: 7 });
const rc = task('c-chase', { p: C, s: 3, title: 'Monthly partner progress report chase', desc: 'Email all partners for their monthly progress note; log who replied.', a: 8, by: 7, due: { sql: `date('now', 'start of month', '+4 days')` }, est: 2, age: 40, check: ['CY', 'RO', 'HR', 'PT', 'GR'] });
out.push(`UPDATE tasks SET recurrence_id = 1 WHERE id = ${rc}; UPDATE recurrences SET source_task_id = ${rc} WHERE id = 1;`);
ins('recurrences', { id: 2, freq: 'monthly', interval_n: 3, by_monthday: -1, mode: 'schedule', next_due: { sql: `date('now', 'start of month', '+4 months', '-1 day')` }, created_by: 9 });
const rt = task('ts-q', { p: N, s: 2, title: 'Quarterly timesheet run', a: 9, by: 9, due: { sql: `date('now', 'start of month', '+1 month', '-1 day')` }, est: 4, labels: [2], age: 60, check: ['Export hours', 'Signatures', 'File in project folder'] });
out.push(`UPDATE tasks SET recurrence_id = 2 WHERE id = ${rt}; UPDATE recurrences SET source_task_id = ${rt} WHERE id = 2;`);

section('Comments with mentions');
const comments = [
  ['y-wp3-m2', 6, 'Draft is about 60% there. @[Eleni Georgiou](user:3) can you look at the structure before I write the activity sheets?', -3],
  ['y-wp3-m2', 3, 'Structure is good. Keep each activity under 45 minutes — youth workers asked for that in the focus groups.', -2],
  ['y-wp3-m1', 5, 'Sent to APE and FES for review. @[Dimitris Kostopoulos](user:4) FES has not acknowledged yet.', -6],
  ['y-wp3-chase', 4, 'Second email sent. If nothing by Friday I will call their coordinator.', -1],
  ['y-int1', 3, '@[Maria Ioannou](user:5) please send your M1–M9 timesheets by next week so Dimitris can assemble the package.', -1],
  ['y-wp3-m4', 14, 'We will deliver a first draft of Module 4 by the due date. Can KMOP share the template again?', -2],
  ['c-ethics', 7, 'RO partner says the committee meets next Tuesday. @[Thomas Verbeke](user:8) please hold the teacher sessions until then.', -1],
  ['c-cur', 8, 'Literature review done. Moving to session plans with Maria.', -20],
  ['n-tender', 9, 'Δύο προσφορές ήρθαν, περιμένουμε την τρίτη. @[Dimitris Kostopoulos](user:4) ενημέρωσε τον προμηθευτή για την προθεσμία.', -2],
  ['n-c1', 11, 'Πρώτη εβδομάδα: 18 από 20 παρόντες.', -4],
];
let cid = 1;
for (const [k, author, body, days] of comments) {
  const project = TP[k];
  ins('comments', { id: cid, object_type: 'task', object_id: T[k], project_id: project, author_id: author, body, created_at: ts(days), updated_at: ts(days) });
  for (const m of body.matchAll(/@\[[^\]]+\]\(user:(\d+)\)/g)) {
    ins('mentions', { comment_id: cid, object_type: 'task', object_id: T[k], user_id: Number(m[1]), author_id: author, created_at: ts(days) });
    ins('notifications', { user_id: Number(m[1]), kind: 'mentioned', actor_id: author, object_type: 'task', object_id: T[k], project_id: project, title: '(see task)', body: body.replace(/@\[([^\]]+)\]\(user:\d+\)/g, '@$1').slice(0, 200), url: `#/tasks/${T[k]}`, dedupe_key: `mention:c${cid}`, created_at: ts(days), read_at: days < -2 ? ts(days + 1) : null });
  }
  out.push(`INSERT OR IGNORE INTO task_followers (task_id, user_id, reason) VALUES (${T[k]}, ${author}, 'commented');`);
  cid++;
}
out.push(`UPDATE notifications SET title = (SELECT title FROM tasks WHERE tasks.id = notifications.object_id) WHERE title = '(see task)';`);

section('More inbox items');
const notes = [
  [5, 'assigned', 3, 'y-wp3-m3', -1], [6, 'assigned', 3, 'y-wp3-m5', -2], [8, 'assigned', 7, 'c-risk', -1], [11, 'assigned', 4, 'n-c3', -3],
  [3, 'completed', 6, 'y-wp3-m2-a', -4], [4, 'overdue', null, 'y-wp3-chase', 0], [6, 'overdue', null, 'y-wp3-m2', 0], [7, 'overdue', null, 'c-ethics', 0],
];
for (const [user_id, kind, actor_id, k, days] of notes) {
  ins('notifications', { user_id, kind, actor_id, object_type: 'task', object_id: T[k], title: { sql: `(SELECT title FROM tasks WHERE id = ${T[k]})` }, project_id: { sql: `(SELECT project_id FROM tasks WHERE id = ${T[k]})` }, url: `#/tasks/${T[k]}`, dedupe_key: `${kind}:${T[k]}:seed`, created_at: ts(days, -2) });
}

section('Activity stream (a little history so feeds are not empty)');
const acts = [
  [3, 'project.created', 'project', 1, 1, null, { name: 'YouthLink' }, -280], [7, 'project.created', 'project', 2, 2, null, { name: 'SAFE' }, -140],
  [6, 'task.completed', 'task', T['y-wp3-m2-a'], 1, T['y-wp3-m2'], { title: 'Collect three example stories from Greek youth centres' }, -4],
  [5, 'task.updated', 'task', T['y-wp3-m1'], 1, T['y-wp3-m1'], { title: 'Module 1 — Online safety', changes: { status: ['in_progress', 'in_review'] } }, -6],
  [10, 'task.completed', 'task', T['c-prefin'], 2, T['c-prefin'], { title: 'Distribute pre-financing to partners' }, -18],
  [12, 'task.completed', 'task', T['h-setup'], 4, T['h-setup'], { title: 'Configure entities, departments and roles' }, -4],
  [4, 'member.added', 'user', 6, 3, null, { name: 'Giorgos Nikolaou', role: 'member' }, -60],
];
for (const [actor_id, verb, object_type, object_id, project_id, task_id, payload, days] of acts) ins('activity', { actor_id, verb, object_type, object_id, project_id, task_id, payload: JSON.stringify(payload), at: ts(days) });
for (const [k, author, , days] of comments) ins('activity', { actor_id: author, verb: 'comment.added', object_type: 'comment', object_id: T[k], project_id: { sql: `(SELECT project_id FROM tasks WHERE id = ${T[k]})` }, task_id: T[k], payload: JSON.stringify({ excerpt: '…' }), at: ts(days) });

section('Audit trail sample');
ins('audit_log', { at: ts(-200), actor_id: 12, action: 'grant', object_type: 'user', object_id: 9, object_label: 'Anna Papadopoulou', entity_id: 1, summary: 'Yannis Markou gave Anna Papadopoulou the Finance role in KMOP ASSOCIATION' });
ins('audit_log', { at: ts(-200), actor_id: 12, action: 'grant', object_type: 'user', object_id: 10, object_label: 'Lucas Dubois', entity_id: 2, summary: 'Yannis Markou gave Lucas Dubois the Finance role in KMOP POLICY CENTER' });
ins('audit_log', { at: ts(-2), actor_id: 12, action: 'grant', object_type: 'user', object_id: 15, object_label: 'Petros Lazaridis', summary: 'Yannis Markou gave Petros Lazaridis the Auditor role in every entity until expiry (45 days)' });
ins('audit_log', { at: ts(-6), actor_id: 5, action: 'update', object_type: 'task', object_id: T['y-wp3-m1'], object_label: 'Module 1 — Online safety', entity_id: 1, project_id: 1, summary: 'Maria Ioannou updated the task "Module 1 — Online safety": changed status from in_progress to in_review', changes: JSON.stringify({ status: ['in_progress', 'in_review'] }) });
ins('audit_log', { at: ts(-18), actor_id: 10, action: 'update', object_type: 'task', object_id: T['c-prefin'], object_label: 'Distribute pre-financing to partners', entity_id: 2, project_id: 2, summary: 'Lucas Dubois updated the task "Distribute pre-financing to partners": changed status from todo to done', changes: JSON.stringify({ status: ['todo', 'done'] }) });

// ---------------------------------------------------------------------------
section('Templates');
const ka220 = {
  sections: [{ name: 'WP1 — Management' }, { name: 'WP2 — Research' }, { name: 'WP3 — Main output' }, { name: 'WP4 — Pilots' }, { name: 'WP5 — Dissemination' }],
  labels: [{ name: 'partner-input', color: '#0ea5e9' }, { name: 'deliverable', color: '#9333ea' }],
  custom_fields: [{ name: 'Lead partner', type: 'text' }, { name: 'Dissemination level', type: 'select', options: [{ key: 'pu', label: 'Public' }, { key: 'se', label: 'Sensitive' }] }],
  tasks: [
    { key: 'kickoff', title: 'Kick-off meeting', section: 'WP1 — Management', due_month: 1, is_milestone: true, assign: 'creator', checklist: ['Agenda', 'Partner presentations', 'Minutes and decisions'] },
    { key: 'qa-plan', title: 'Quality assurance plan', section: 'WP1 — Management', due_month: 3, labels: ['deliverable'], blocked_by: ['kickoff'] },
    { key: 'dmp', title: 'Dissemination & exploitation plan', section: 'WP5 — Dissemination', due_month: 3, labels: ['deliverable'], blocked_by: ['kickoff'] },
    { key: 'research', title: 'Comparative research report', section: 'WP2 — Research', start_month: 2, due_month: 6, labels: ['deliverable', 'partner-input'], subtasks: [
      { key: 'desk', title: 'Desk research per country', due_month: 4, labels: ['partner-input'] },
      { key: 'fg', title: 'Focus groups per country', due_month: 5, labels: ['partner-input'] },
      { key: 'synth', title: 'Synthesis report', due_month: 6, blocked_by: ['desk', 'fg'] } ] },
    { key: 'interim', title: 'Interim report to the National Agency', section: 'WP1 — Management', due_month: 12, labels: ['partner-input'], checklist: ['Narrative per WP', 'Timesheets', 'Dissemination evidence', 'Financial statement'] },
    { key: 'output', title: 'Main result (toolkit / curriculum / platform)', section: 'WP3 — Main output', start_month: 6, due_month: 14, labels: ['deliverable'], blocked_by: ['research'] },
    { key: 'pilot', title: 'Pilots in each country', section: 'WP4 — Pilots', start_month: 15, due_month: 18, blocked_by: ['output'] },
    { key: 'me', title: 'Multiplier events', section: 'WP5 — Dissemination', due_month: 22 },
    { key: 'final', title: 'Final report', section: 'WP1 — Management', due_month: 24, is_milestone: true, blocked_by: ['pilot'] },
  ],
};
ins('project_templates', { id: 1, name: 'Erasmus+ KA220 cooperation partnership (24 months)', description: 'Standard KA2 skeleton: five work packages, research → main output → pilots, interim report at M12, final at M24. Due dates are project months.', kind: 'eu', body: JSON.stringify(ka220), created_by: 3 });
const espa = {
  sections: [{ name: 'Προετοιμασία' }, { name: 'Υλοποίηση' }, { name: 'Παρακολούθηση' }],
  tasks: [
    { key: 'inc', title: 'Έλεγχος απόφασης ένταξης', section: 'Προετοιμασία', due_offset: 7, assign: 'creator' },
    { key: 'proc', title: 'Διαδικασίες προμηθειών', section: 'Προετοιμασία', due_offset: 45, blocked_by: ['inc'] },
    { key: 'impl', title: 'Υλοποίηση φυσικού αντικειμένου', section: 'Υλοποίηση', start_offset: 30, due_offset: 300 },
    { key: 'q1', title: 'Τριμηνιαίο δελτίο παρακολούθησης', section: 'Παρακολούθηση', due_offset: 90 },
    { key: 'pay1', title: 'Αίτημα καταβολής 1ης δόσης', section: 'Παρακολούθηση', due_offset: 120, blocked_by: ['q1'] },
  ],
};
ins('project_templates', { id: 2, name: 'ΕΣΠΑ — πράξη κατάρτισης (εθνικό)', description: 'National ESPA training action: procurement, implementation, quarterly physical-progress reports, instalment requests.', kind: 'national', entity_id: 3, body: JSON.stringify(espa), created_by: 4 });
ins('task_templates', { id: 1, name: 'Monthly partner report chase', body: JSON.stringify({ title: 'Partner progress report chase', description: 'Email all partners for their monthly progress note; log who replied.', estimate_hours: 2, checklist: ['Send reminder', 'Log replies', 'Escalate non-responders to PM'] }), created_by: 7 });
ins('task_templates', { id: 2, name: 'Quarterly timesheet run', body: JSON.stringify({ title: 'Quarterly timesheet run', estimate_hours: 4, checklist: ['Export hours', 'Collect signatures', 'File in project folder'], subtasks: [{ title: 'Remind staff to submit timesheets' }, { title: 'Check against allocations' }] }), created_by: 9 });

section('Saved views');
ins('saved_views', { user_id: 3, scope: 'project:1', name: 'WP3 — open', view_type: 'list', config: JSON.stringify({ filters: { section_id: String(S['1:2']), state: 'open' } }) });
ins('saved_views', { user_id: 3, scope: 'my_tasks', name: 'High priority', view_type: 'list', config: JSON.stringify({ filters: { priority: 'high,urgent' } }) });
ins('saved_views', { user_id: 7, scope: 'project:2', name: 'Board by status', view_type: 'board', config: JSON.stringify({ group: 'status' }), shared: 1 });

section('Access model (role + module grants + supervised projects) — same rules as migration 005');
out.push(...readFileSync(new URL('../migrations/005_roles_modules_google.sql', import.meta.url), 'utf8')
  .split('\n').filter(l => /^(UPDATE users SET role|INSERT OR IGNORE INTO (module_grants|supervisor_projects)|  SELECT|   WHERE)/.test(l)));
// A KMOP member with a narrower set, to show module access: Christina sees Tasks and Running projects only.
out.push(`DELETE FROM module_grants WHERE user_id = 11 AND module NOT IN ('projects','tasks');`);

writeFileSync(new URL('../data/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log(`data/seed.sql: ${out.length} lines, ${tid - 1} tasks`);
